In [19]:
import os
from pathlib import Path
import pandas as pd

CUR_DIR = os.path.abspath('')
DATA_DIR = Path(CUR_DIR).parent / "data" / "millionsong"

Read the first triplets.txt file

In [20]:
FILE_PATH = DATA_DIR/'train_triplets.txt'
df_triplets = pd.read_csv(FILE_PATH,
                          names=['user', 'track_id', 'listening_count'], sep = '\t')

In [21]:
df_triplets.head()

user            track_id  \
0  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOAKIMP12A8C130995   
1  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOAPDEY12A81C210A9   
2  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBBMDR12A8C13253B   
3  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBFNSP12AF72A0E22   
4  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBFOVM12A58A7D494   

   listening_count  
0                1  
1                1  
2                2  
3                1  
4                1

In [22]:
df_triplets.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48373586 entries, 0 to 48373585
Data columns (total 3 columns):
 #   Column           Dtype 
---  ------           ----- 
 0   user             object
 1   track_id         object
 2   listening_count  int64 
dtypes: int64(1), object(2)
memory usage: 1.1+ GB


In [23]:
df_triplets.describe()

listening_count
count     4.837359e+07
mean      2.866859e+00
std       6.437725e+00
min       1.000000e+00
25%       1.000000e+00
50%       1.000000e+00
75%       3.000000e+00
max       9.667000e+03

In [24]:
df_triplets.isna().sum()

user               0
track_id           0
listening_count    0
dtype: int64

In [25]:
df_triplets.duplicated().sum()

0

In [26]:
print("user nunique: ", df_triplets['user'].nunique())
print("track id nunique: ",df_triplets['track_id'].nunique())

user nunique:  1019318
track id nunique:  384546


Load the second file track_metadata.db containing tracks informations

In [27]:
CUR_DIR = DATA_DIR / 'track_metadata.db'
import numpy as np

import sqlite3
from pandas import read_sql_query, read_sql_table
with sqlite3.connect(CUR_DIR) as dbcon:
    tables = list(read_sql_query("SELECT name FROM sqlite_master WHERE type='table';", dbcon)['name'])
    df_metadata = {tbl : read_sql_query(f"SELECT * from {tbl}", dbcon) for tbl in tables}
    #print(df_metadata)
print(df_metadata.keys())
print(df_metadata.items())
df_metadata = pd.DataFrame.from_dict(df_metadata['songs'])

dict_keys(['songs'])
dict_items([('songs',                   track_id                                title  \
0       TRMMMYQ128F932D901                         Silent Night   
1       TRMMMKD128F425225D                          Tanssi vaan   
2       TRMMMRX128F93187D9                    No One Could Ever   
3       TRMMMCH128F425532C                        Si Vos Querés   
4       TRMMMWA128F426B589                     Tangle Of Aspens   
...                    ...                                  ...   
999995  TRYYYUS12903CD2DF0                      O Samba Da Vida   
999996  TRYYYJO128F426DA37                         Jago Chhadeo   
999997  TRYYYMG128F4260ECA                              Novemba   
999998  TRYYYDJ128F9310A21                              Faraday   
999999  TRYYYVU12903CD01E3  Fernweh feat. Sektion Kuchikäschtli   

                   song_id                               release  \
0       SOQMMHC12AB0180CB8                 Monster Ballads X-Mas   
1       SOVFVAK1

In [28]:
df_metadata

track_id                                title  \
0       TRMMMYQ128F932D901                         Silent Night   
1       TRMMMKD128F425225D                          Tanssi vaan   
2       TRMMMRX128F93187D9                    No One Could Ever   
3       TRMMMCH128F425532C                        Si Vos Querés   
4       TRMMMWA128F426B589                     Tangle Of Aspens   
...                    ...                                  ...   
999995  TRYYYUS12903CD2DF0                      O Samba Da Vida   
999996  TRYYYJO128F426DA37                         Jago Chhadeo   
999997  TRYYYMG128F4260ECA                              Novemba   
999998  TRYYYDJ128F9310A21                              Faraday   
999999  TRYYYVU12903CD01E3  Fernweh feat. Sektion Kuchikäschtli   

                   song_id                               release  \
0       SOQMMHC12AB0180CB8                 Monster Ballads X-Mas   
1       SOVFVAK12A8C1350D9                           Karkuteillä   
2       SOGTUKN12AB017F4F1                                Butter   
3       SOBNYVR12A8C13558C                               De Culo   
4       SOHSBXH12A8C13B0DF  Rene Ablaze Presents Winter Sessions   
...                    ...                                   ...   
999995  SOTXAME12AB018F136                          Pacha V.I.P.   
999996  SOXQYIQ12A8C137FBB              Naale Baba Lassi Pee Gya   
999997  SOHODZI12A8C137BB3       Dub_Connected: electronic music   
999998  SOLXGOR12A81C21EB7          The Trance Collection Vol. 2   
999999  SOWXJXQ12AB0189F43                            So Oder So   

                 artist_id                           artist_mbid  \
0       ARYZTJS1187B98C555  357ff05d-848a-44cf-b608-cb34b5701ae5   
1       ARMVN3U1187FB3A1EB  8d7ef530-a6fd-4f8f-b2e2-74aec765e0f9   
2       ARGEKB01187FB50750  3d403d44-36ce-465c-ad43-ae877e65adc4   
3       ARNWYLR1187B9B2F9C  12be7648-7094-495f-90e6-df4189d68615   
4       AREQDTE1269FB37231                                         
...                    ...                                   ...   
999995  AR7Z4J81187FB3FC59  9d50cb20-7e42-45cc-b0dd-154c3e92a577   
999996  ART5FZD1187B9A7FCF  2357c400-9109-42b6-b3fe-9e2d9f8e3872   
999997  ARZ3R6M1187B9AF750  8b97e9c8-61f5-4615-9a96-276f24204e34   
999998  ARCMCOK1187B9B1073  4ac5f3de-c5ad-475e-ad50-41f1ef9dba20   
999999  AR7PLM21187B990D08  3af2b07e-c91c-4160-9bda-f0b9e3144ed3   

             artist_name   duration  artist_familiarity  artist_hotttnesss  \
0       Faster Pussy cat  252.05506            0.649822           0.394032   
1       Karkkiautomaatti  156.55138            0.439604           0.356992   
2         Hudson Mohawke  138.97098            0.643681           0.437504   
3            Yerba Brava  145.05751            0.448501           0.372349   
4             Der Mystic  514.29832            0.000000           0.000000   
...                  ...        ...                 ...                ...   
999995      Kiko Navarro  217.44281            0.528617           0.411595   
999996     Kuldeep Manak  244.16608            0.401500           0.374866   
999997    Gabriel Le Mar  553.03791            0.556918           0.336914   
999998             Elude  484.51873            0.403668           0.256935   
999999             Texta  295.07873            0.552977           0.454869   

        year  track_7digitalid  shs_perf  shs_work  
0       2003           7032331        -1         0  
1       1995           1514808        -1         0  
2       2006           6945353        -1         0  
3       2003           2168257        -1         0  
4          0           2264873        -1         0  
...      ...               ...       ...       ...  
999995     0           7522478        -1         0  
999996     0           1632096        -1         0  
999997     0           2219291        -1         0  
999998     0           5472456        -1         0  
999999  2004           8486723        -1         0  

[1000

In [29]:
df_metadata['song_id'].isin(df_triplets['track_id']).sum()

385256

Rename df_triplets track_id key into song_id key to merge the two dataframes

In [30]:
df_triplets = df_triplets.rename(columns = {'track_id' : 'song_id'})

In [31]:
print(df_metadata['song_id'].duplicated().sum())
df_metadata[df_metadata['song_id'].duplicated()]

944


track_id                      title             song_id  \
18309   TRMNFVE128F932907E             Spitting Games  SOPFBUZ12AF729C896   
32760   TRMDYQQ128F428080C  A Crow Left Of The Murder  SOJHKXX12A8C139798   
33033   TRMOHMT128F92FD3D3              What If I Do?  SOLTAEJ12A8C13F793   
49718   TRWFAGT128F4213B6E          Starfighter Pilot  SONEJDQ12A6D4FA71C   
54218   TRWIPEU128E078997D   The Damage In Your Heart  SONVJUL12A6701FB7A   
...                    ...                        ...                 ...   
997476  TRYKFLS128E078462C                 Yesterdays  SOCGXXL12B0B808865   
998785  TRYYROY128F92CBEF4  Someone Put Your Hand Out  SOEUIVS12A8C1400E3   
999365  TRYYUXT128F42143B0             Long Way To Go  SORANLE12A6310DBC8   
999643  TRYYVPJ128F427E2ED                Suggestions  SOAPUFN12AB017FF03   
999740  TRYYOWT128F42B6558           Ruled By Secrecy  SODNVTM12A6D4FA448   

                              release           artist_id  \
18309                     Final Straw  ARVN9FZ1187FB393F1   
32760           Live in Malaysia 2004  AR1RMYB1187FB5A59E   
33033                   In Your Honor  AR6XPWV1187B9ADAEB   
49718            Songs For Polarbears  ARVN9FZ1187FB393F1   
54218                    Make Believe  AR633SY1187B9AC3B9   
...                               ...                 ...   
997476                  Greatest Hits  ARM7EDF1187B9B3FA1   
998785                    King Of Pop  ARXPPEY1187FB51DF4   
999365          Love Angel Music Baby  ARVBRGZ1187FB4675A   
999643  System Of A Down (Bonus Pack)  AR9C8IE1187B9ACC99   
999740                     Absolution  ARR3ONV1187B9A2F59   

                                 artist_mbid                artist_name  \
18309   a66999a7-ae5c-460e-ba94-1a01143ae847                Snow Patrol   
32760   e3e0abcd-7671-4482-a9d8-462f5acc9be5                    Incubus   
33033   67f66c07-6e61-4026-ade5-7e782fad3a5d               Foo Fighters   
49718   a66999a7-ae5c-460e-ba94-1a01143ae847                Snow Patrol   
54218   6fe07aa5-fec0-4eca-a456-f29bff451b04                     Weezer   
...                                      ...                        ...   
997476  eeb1195b-f213-4ce1-b28c-8565211f8e43              Guns N' Roses   
998785  f27ec8db-af05-4f36-916e-3d57f91ecf5e            Michael Jackson   
999365  2e41ae9c-afd2-4f20-8f1e-17281ce9b472  Gwen Stefani / Andre 3000   
999643  cc0b7089-c08d-4c10-b6b0-873582c17fd6           System of a Down   
999740  fd857293-5ab8-40de-b29e-55a69d4e4d0f                       Muse   

         duration  artist_familiarity  artist_hotttnesss  year  \
18309   227.60444            0.818319           0.667295  2003   
32760   222.74567            0.899280           0.605604  2004   
33033   302.91546            0.839275           0.550762  2005   
49718   199.67955            0.818319           0.667295  1998   
54218   242.93832            0.830885           0.776168  2005   
...           ...                 ...                ...   ...   
997476  194.45506            0.844085           0.701980  1991   
998785  324.62322            0.866520           0.808502  1992   
999365  274.02404            0.837872           0.532804     0   
999643  163.94404            0.909958           0.609262  1998   
999740  292.28363            0.929030           0.750427     0   

        track_7digitalid  shs_perf  shs_work  
18309            5573436        -1         0  
32760            3282110        -1         0  
33033            4931403        -1         0  
49718            2469065        -1         0  
54218             116881        -1         0  
...                  ...       ...       ...  
997476             23513        -1         0  
998785           3576380        -1         0  
999365           2471232        -1         0  
999643           3272607        -1         0  
999740           3505486        -1         0  

[944 rows x 14 columns]

In [32]:
#df_metadata[df_metadata['song_id']=="SOPFBUZ12AF729C896"]
df_metadata[df_metadata['song_id']=="SODNVTM12A6D4FA448"]

track_id             title             song_id     release  \
766340  TRSXXLJ128F932B6F2  Ruled By Secrecy  SODNVTM12A6D4FA448  Absolution   
999740  TRYYOWT128F42B6558  Ruled By Secrecy  SODNVTM12A6D4FA448  Absolution   

                 artist_id                           artist_mbid artist_name  \
766340  ARR3ONV1187B9A2F59  fd857293-5ab8-40de-b29e-55a69d4e4d0f        Muse   
999740  ARR3ONV1187B9A2F59  fd857293-5ab8-40de-b29e-55a69d4e4d0f        Muse   

         duration  artist_familiarity  artist_hotttnesss  year  \
766340  292.28363             0.92903           0.791501     0   
999740  292.28363             0.92903           0.750427     0   

        track_7digitalid  shs_perf  shs_work  
766340           5134212        -1         0  
999740           3505486        -1         0

In the metadata dataframe, some songs are duplicates

In [33]:
df_metadata = df_metadata.drop_duplicates(subset = ['song_id'], keep='first')
df_metadata['song_id'].duplicated().sum()

0

Now let's merge the two dataframes on the common key song_id

In [34]:
df_triplets_metadata = pd.merge(df_triplets, df_metadata, on = 'song_id', how = 'inner')
df_triplets_metadata

user             song_id  \
0         b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOAKIMP12A8C130995   
1         7c86176941718984fed11b7c0674ff04c029b480  SOAKIMP12A8C130995   
2         76235885b32c4e8c82760c340dc54f9b608d7d7e  SOAKIMP12A8C130995   
3         250c0fa2a77bc6695046e7c47882ecd85c42d748  SOAKIMP12A8C130995   
4         3f73f44560e822344b0fb7c6b463869743eb9860  SOAKIMP12A8C130995   
...                                            ...                 ...   
48373581  7e5ee985d8df64ef746a8c374357d7f39ccfcb61  SOJLGCD12A6D4F4A7C   
48373582  ac96070188fa5618d5e1595937f6e02b4ab4a4fa  SONYEUK12A8C13E9A4   
48373583  b691b8eda35349ebaf4801c5c56a399273b6157c  SOUSSCZ12A8C131D83   
48373584  12bce146f59c4e6d32e1a460468197cfd7cf14e8  SOKSHWF12AB018B8CC   
48373585  6428bbc86c59bd5d1d289935056b57acd0e050ad  SOCDLVW12AB018371F   

          listening_count            track_id                         title  \
0                       1  TRIQAUQ128F42435AD                      The Cove   
1                       1  TRIQAUQ128F42435AD                      The Cove   
2                       3  TRIQAUQ128F42435AD                      The Cove   
3                       1  TRIQAUQ128F42435AD                      The Cove   
4                       6  TRIQAUQ128F42435AD                      The Cove   
...                   ...                 ...                           ...   
48373581                1  TRSZCYV128F1467F70                      The Ring   
48373582                1  TRHPXTA128F428EFA2                      Mi Dueña   
48373583                2  TRRIYUS128F423F27F           Concert For A Queen   
48373584                3  TRBVDMB12903CC45BB  Then There's Me (LP Version)   
48373585                5  TRASFAV128F93428A4                        Rowena   

                                                   release  \
0                                       Thicker Than Water   
1                                       Thicker Than Water   
2                                       Thicker Than Water   
3                                       Thicker Than Water   
4                                       Thicker Than Water   
...                                                    ...   
48373581                                               Gag   
48373582                                     Desde Mi Alma   
48373583                                     Rainbow's End   
48373584                                       Tim Rushlow   
48373585  High Wide & Handsome - The Charlie Poole Project   

                   artist_id                           artist_mbid  \
0         ARC8CQZ1187B98DECA  ff6e677f-91dd-4986-a174-8db0474b1799   
1         ARC8CQZ1187B98DECA  ff6e677f-91dd-4986-a174-8db0474b1799   
2         ARC8CQZ1187B98DECA  ff6e677f-91dd-4986-a174-8db0474b1799   
3         ARC8CQZ1187B98DECA  ff6e677f-91dd-4986-a174-8db0474b1799   
4         ARC8CQZ1187B98DECA  ff6e677f-91dd-4986-a174-8db0474b1799   
...                      ...                                   ...   
48373581  AR9JO951187FB53146  5c96def1-68a5-4aa3-8f71-3ae427a33eb4   
48373582  ARLDX1T1187B991E69  3be3d51b-dcef-405d-8102-96959adfc35e   
48373583  ARVMOYN1187B9AB86C  cbf344ae-68f6-45c8-9b52-fcb25dce4646   
48373584  ARLDSCZ1187FB5757D  30c01706-b4ae-4fe0-9d38-1f54f01e6c36   
48373585  ARV1JVD1187B9AD195  3ddc1fe4-0abb-4af0-9392-e36720386842   

                    artist_name   duration  artist_familiarity  \
0                  Jack Johnson  112.63955            0.832012   
1                  Jack Johnson  112.63955            0.832012   
2                  Jack Johnson  112.63955            0.832012   
3                  Jack Johnson  112.63955            0.832012   
4                  Jack Johnson  112.63955            0.832012   
...                         ...        ...                 ...   
48373581             Fad Gadget  233.27302            0.596516   
48373582              Joe Veras  258.53342            0.566008   
48373583               Rez B

In [37]:
print("NaNs: ", df_triplets_metadata.isna().sum())

NaNs:  user                  0
song_id               0
listening_count       0
track_id              0
title                 0
release               0
artist_id             0
artist_mbid           0
artist_name           0
duration              0
artist_familiarity    0
artist_hotttnesss     0
year                  0
track_7digitalid      0
shs_perf              0
shs_work              0
dtype: int64


In [38]:
print("Duplicated: ", df_triplets_metadata.duplicated().sum())

Duplicated:  0


In [36]:
print(len(df_triplets.index))
print(len(df_triplets_metadata.index))

48373586
48373586


# Kept only one occurence of metadata.db song_id 
# Which results in an inner join merge with the same number of values between triplets and triplets/metadata merge

In [ ]:
#DESTINATION_PATH = DATA_DIR / 'triplets_metadata.csv'
#df_triplets_metadata.to_csv(DESTINATION_PATH)

In [ ]:

FILE_PATH = DATA_DIR/'triplets_metadata.csv'

df_triplets_metadata = pd.read_csv(FILE_PATH)

Let's load the spotify dataset containing acoustic characteristics variables

In [ ]:
FILE_PATH = DATA_DIR / "tracks_features.csv"
df_spotify = pd.read_csv(FILE_PATH)

In [ ]:
df_spotify

id                   name   
0        7lmeHLHBe4nmXzuXc0HDjk                Testify  \
1        1wsRitfRRtWyEapl0q22o8        Guerrilla Radio   
2        1hR0fIFK2qRG3f3RF70pb7       Calm Like a Bomb   
3        2lbASgTSoDO7MTuLAXlTW0              Mic Check   
4        1MQTmpYOZ6fcMQc56Hdo7T  Sleep Now In the Fire   
...                         ...                    ...   
1204020  0EsMifwUmMfJZxzoMPXJKZ         Gospel of Juke   
1204021  2WSc2TB1CSJgGE0PEzVeiu          Prism Visions   
1204022  6iProIgUe3ETpO6UT0v5Hg              Tokyo 360   
1204023  37B4SXC8uoBsUyKCWnhPfX                 Yummy!   
1204024  3GgQmOxxLyRoAb4j86zOBX   That's The Way It Is   

                             album                album_id   
0        The Battle Of Los Angeles  2eia0myWFgoHuttJytCxgX  \
1        The Battle Of Los Angeles  2eia0myWFgoHuttJytCxgX   
2        The Battle Of Los Angeles  2eia0myWFgoHuttJytCxgX   
3        The Battle Of Los Angeles  2eia0myWFgoHuttJytCxgX   
4        The Battle Of Los Angeles  2eia0myWFgoHuttJytCxgX   
...                            ...                     ...   
1204020                 Notch - EP  38O5Ys0W9PFS5K7dMb7yKb   
1204021                 Notch - EP  38O5Ys0W9PFS5K7dMb7yKb   
1204022                 Notch - EP  38O5Ys0W9PFS5K7dMb7yKb   
1204023                 Notch - EP  38O5Ys0W9PFS5K7dMb7yKb   
1204024                 Notch - EP  38O5Ys0W9PFS5K7dMb7yKb   

                              artists                  artist_ids   
0        ['Rage Against The Machine']  ['2d0hyoQ5ynDBnkvAbJKORj']  \
1        ['Rage Against The Machine']  ['2d0hyoQ5ynDBnkvAbJKORj']   
2        ['Rage Against The Machine']  ['2d0hyoQ5ynDBnkvAbJKORj']   
3        ['Rage Against The Machine']  ['2d0hyoQ5ynDBnkvAbJKORj']   
4        ['Rage Against The Machine']  ['2d0hyoQ5ynDBnkvAbJKORj']   
...                               ...                         ...   
1204020                   ['FVLCRVM']  ['7AjItKsRnEYRSiBt2OxK1y']   
1204021                   ['FVLCRVM']  ['7AjItKsRnEYRSiBt2OxK1y']   
1204022                   ['FVLCRVM']  ['7AjItKsRnEYRSiBt2OxK1y']   
1204023                   ['FVLCRVM']  ['7AjItKsRnEYRSiBt2OxK1y']   
1204024                   ['FVLCRVM']  ['7AjItKsRnEYRSiBt2OxK1y']   

         track_number  disc_number  explicit  danceability  ...  speechiness   
0                   1            1     False         0.470  ...       0.0727  \
1                   2            1      True         0.599  ...       0.1880   
2                   3            1     False         0.315  ...       0.4830   
3                   4            1      True         0.440  ...       0.2370   
4                   5            1     False         0.426  ...       0.0701   
...               ...          ...       ...           ...  ...          ...   
1204020             2            1     False         0.264  ...       0.0672   
1204021             3            1     False         0.796  ...       0.0883   
1204022             4            1     False         0.785  ...       0.0564   
1204023             5            1     False         0.665  ...       0.0409   
1204024             6            1     False         0.736  ...       0.0539   

         acousticness  instrumentalness  liveness  valence    tempo   
0             0.02610          0.000011    0.3560    0.503  117.906  \
1             0.01290          0.000071    0.1550    0.489  103.680   
2             0.02340          0.000002    0.1220    0.370  149.749   
3             0.16300          0.000004    0.1210    0.574   96.752   
4             0.00162          0.105000    0.0789    0.539  127.059   
...               ...               ...       ...      ...      ...   
1204020       0.00935          0.002240    0.3370    0.415  159.586   
1204021       0.10400          0.644000    0.0749    0.781  121.980   
1204022       0.03040          0.918000    0.0664    0.467  121.996   
1204023       0.00007          0.776000    0.1170    0.227  124.986   
1204024       0.

In [ ]:
df_spotify.columns

Index(['id', 'name', 'album', 'album_id', 'artists', 'artist_ids',
       'track_number', 'disc_number', 'explicit', 'danceability', 'energy',
       'key', 'loudness', 'mode', 'speechiness', 'acousticness',
       'instrumentalness', 'liveness', 'valence', 'tempo', 'duration_ms',
       'time_signature', 'year', 'release_date'],
      dtype='object')

In [ ]:
print(df_spotify['name'].isin(df_triplets_metadata['title']).sum())

299832


In [ ]:
df_spotify['name'].duplicated().sum()

353081

In [ ]:
df_spotify[df_spotify['name'].duplicated()]

id                  name   
121      4FcpCdqGjleaRZBFvVcHmq                 Swing  \
279      6gzMTey1L7RDVkYB6KVREd             Thank You   
310      3f7Ktj0FIWGDH96PSRl4AF               Tell Me   
318      3ESOHGGy5iudYxsKos0Nmm            Going Down   
367      2ZC5ygLIJEMuLTiElPFTnC          Rock Me Baby   
...                         ...                   ...   
1204014  42vPp4aj2UU70f7Telce6f  Too Good at Goodbyes   
1204015  4pKo5WZVdZJ6J5rR8RS079         Drop the Game   
1204017  4YSFJEEMSPJpY1xp6VOyc0    Wayfaring Stranger   
1204019  09pq2M9MffFVf0Ha4og87y           Work It Out   
1204024  3GgQmOxxLyRoAb4j86zOBX  That's The Way It Is   

                            album                album_id   
121                  To The Teeth  2gH0pLuQAJm9eWxIM87lSy  \
279                    Turnaround  7cAUnQdYOGT2q0OPiBgTWO   
310      The Complete Stone Roses  2X30YPHjEbDLtxwsHnUabT   
318      The Complete Stone Roses  2X30YPHjEbDLtxwsHnUabT   
367          Still Alive And Well  028UyLRMn9HnuTvRaWAVTF   
...                           ...                     ...   
1204014           Visionaire - EP  6aHlKXvgMOgKxwQDCadMin   
1204015            Wayfairer - EP  5K45d2l5PJXVy5ESK0gKg2   
1204017            Wayfairer - EP  5K45d2l5PJXVy5ESK0gKg2   
1204019                Notch - EP  38O5Ys0W9PFS5K7dMb7yKb   
1204024                Notch - EP  38O5Ys0W9PFS5K7dMb7yKb   

                         artists                  artist_ids  track_number   
121             ['Ani DiFranco']  ['0AiTwNtYX8m4uhfU7rJ8RD']             8  \
279                 ['Westlife']  ['5Z1CCuBsyhEHngq3U5IraY']             9   
310          ['The Stone Roses']  ['1lYT0A0LV5DUfxr6doRP3d']             2   
318          ['The Stone Roses']  ['1lYT0A0LV5DUfxr6doRP3d']            10   
367            ['Johnny Winter']  ['2ODUxmFxJSyvGiimNhMHbO']             1   
...                          ...                         ...           ...   
1204014  ['The Dartmouth Aires']  ['71Cez1b1NqsxIn5u8XNiQD']             4   
1204015  ['The Dartmouth Aires']  ['71Cez1b1NqsxIn5u8XNiQD']             1   
1204017  ['The Dartmouth Aires']  ['71Cez1b1NqsxIn5u8XNiQD']             3   
1204019              ['FVLCRVM']  ['7AjItKsRnEYRSiBt2OxK1y']             1   
1204024              ['FVLCRVM']  ['7AjItKsRnEYRSiBt2OxK1y']             6   

         disc_number  explicit  danceability  ...  speechiness  acousticness   
121                1     False         0.853  ...       0.1410      0.493000  \
279                1     False         0.665  ...       0.0327      0.031900   
310                1     False         0.315  ...       0.0565      0.000235   
318                1     False         0.541  ...       0.0286      0.144000   
367                1     False         0.483  ...       0.0562      0.304000   
...              ...       ...           ...  ...          ...           ...   
1204014            1     False         0.452  ...       0.0275      0.439000   
1204015            1     False         0.398  ...       0.0311      0.764000   
1204017            1     False         0.262  ...       0.0379      0.656000   
1204019            1     False         0.502  ...       0.0667      0.000052   
1204024            1     False         0.736  ...       0.0539      0.016800   

         instrumentalness  liveness  valence    tempo  duration_ms   
121              0.000039    0.1160    0.560   91.829       370027  \
279              0.000000    0.4360    0.932  103.032       242987   
310              0.001190    0.1600    0.475  144.383       230200   
318              0.137000    0.1420    0.673  122.049       166240   
367              0.093500    0.1330    0.647   95.477       229093   
...                   ...       ...      ...      ...          ...   
1204014          0.000000    0.1410    0.214   94.854       199069   
1204015          0.000000    0.0954    0.362   76.508       193445   
1204017          0.000000    0.1130    0.285   90.301       197811   
1204019      

In [ ]:
df_spotify[df_spotify['name'] == 'Swing']

id   name                         album   
102      4piMTKQtY9yMu11VowfZ1E  Swing                 Waste Of Mind  \
121      4FcpCdqGjleaRZBFvVcHmq  Swing                  To The Teeth   
104264   2kIbIq2lYL6BsSZyvhrMOe  Swing                   The Reverie   
125985   7E9zArQHXYkbc8AFXjfQX8  Swing                         Swing   
723857   7iUsbli5HOxD7GX3bVlVfG  Swing                     Cranberry   
872934   1GBOG2XUNOlebG1RY0QSWu  Swing                       Wildboy   
914047   4eSPwTzyVvjHww6izZJ8Oo  Swing                       Wildboy   
994091   566KbrNjXfKAa9XPBzhKRM  Swing  Darklands (Expanded Version)   
994501   52zFdgyz4XD6C1XStFtPOP  Swing         Uptown Saturday Night   
1064018  3wvDzV6339JwGb9MCZEK24  Swing                         Swing   
1183172  6HTrUNIfjfGe6C1HYjBsvx  Swing       Every Little Everything   
1192957  74UEhjwxa2Onj6Zjg1wAqT  Swing           Symptoms of Slavery   

                       album_id                       artists   
102      7bYhJeHWcA2fQcrdLEI5gJ                 ['zebrahead']  \
121      2gH0pLuQAJm9eWxIM87lSy              ['Ani DiFranco']   
104264   5bldzkRIauSNAQFxe3MaLt                ['Beth Amsel']   
125985   3m247h5c1JXymJ1rxMxW0H           ['Anne E. DeChant']   
723857   4MccPvxiSeCuxA6WQJuZeM                    ['Hovvdy']   
872934   1gI3K6X1M3ZuPV6UhkC1Js                    ['Calboy']   
914047   6gH6TAkytLzyXYiTbJQL0O                    ['Calboy']   
994091   5cFb5EJLTQ7u6YuGE922tu  ['The Jesus and Mary Chain']   
994501   21EglTSwzUorpiXpMBNW2E                   ['Camp Lo']   
1064018  3hIqkR93xGR7XXkMvj0M6q       ['Yourmomlikesmymusic']   
1183172  6mOccFzmUQzCtN67fH3vuz           ['Anne E. DeChant']   
1192957  60YOEXhCJXlztv1yMbzORU       ['MoeSOS DC', 'Louis.']   

                                                artist_ids  track_number   
102                             ['6SiyKSeJo6gcsS2NvuAbsl']             9  \
121                             ['0AiTwNtYX8m4uhfU7rJ8RD']             8   
104264                          ['15kMuOBLGJlK4al5SlaAJI']             5   
125985                          ['1V8kWabVDZmxWBKYMWRw4d']             1   
723857                          ['59RNNqeEfkq3X5pfOQxZ3C']            12   
872934                          ['0HkcYmcjrBR3SCw9Ld5VZk']             8   
914047                          ['0HkcYmcjrBR3SCw9Ld5VZk']             8   
994091                          ['4rjlerN21ygkIhmUv55irs']            32   
994501                          ['4oLZx5FplbgfM8DEe9U8LB']             8   
1064018                         ['0MIehjBLCitJ9RQQXEzeS4']             1   
1183172                         ['1V8kWabVDZmxWBKYMWRw4d']            15   
1192957  ['0W9okXAp3gcmaRTAOHol7G', '7lPprXe7cpkFZO2NOv...             9   

         disc_number  explicit  danceability  ...  speechiness  acousticness   
102                1     False         0.658  ...       0.0856      0.000081  \
121                1     False         0.853  ...       0.1410      0.493000   
104264             1     False         0.727  ...       0.0559      0.660000   
125985             1     False         0.473  ...       0.0407      0.013500   
723857             1     False         0.673  ...       0.0314      0.580000   
872934             1     False         0.677  ...       0.1190      0.068200   
914047             1      True         0.683  ...       0.0993      0.064400   
994091             1     False         0.587  ...       0.0280      0.001530   
994501             1     False         0.744  ...       0.3430      0.041100   
1064018            1     False         0.710  ...       0.3770      0.425000   
1183172            1     False         0.543  ...       0.0361      0.054100   
1192957            1      True         0.690  ...       0.1600      0.098500   

         instrumentalness  liveness  valence    tempo  duration_ms   
102              0.000095    0.4820    0.713  120.783       170293  \
121              0.000039    0.1160    0.560   91.829       370027   
104264

In [ ]:
df_spotify['artists'] = df_spotify['artists'].str.strip('[]').astype(str)
df_spotify['artists'] = df_spotify['artists'].str.strip("'").astype(str)
df_spotify

id                   name   
0        7lmeHLHBe4nmXzuXc0HDjk                Testify  \
1        1wsRitfRRtWyEapl0q22o8        Guerrilla Radio   
2        1hR0fIFK2qRG3f3RF70pb7       Calm Like a Bomb   
3        2lbASgTSoDO7MTuLAXlTW0              Mic Check   
4        1MQTmpYOZ6fcMQc56Hdo7T  Sleep Now In the Fire   
...                         ...                    ...   
1204020  0EsMifwUmMfJZxzoMPXJKZ         Gospel of Juke   
1204021  2WSc2TB1CSJgGE0PEzVeiu          Prism Visions   
1204022  6iProIgUe3ETpO6UT0v5Hg              Tokyo 360   
1204023  37B4SXC8uoBsUyKCWnhPfX                 Yummy!   
1204024  3GgQmOxxLyRoAb4j86zOBX   That's The Way It Is   

                             album                album_id   
0        The Battle Of Los Angeles  2eia0myWFgoHuttJytCxgX  \
1        The Battle Of Los Angeles  2eia0myWFgoHuttJytCxgX   
2        The Battle Of Los Angeles  2eia0myWFgoHuttJytCxgX   
3        The Battle Of Los Angeles  2eia0myWFgoHuttJytCxgX   
4        The Battle Of Los Angeles  2eia0myWFgoHuttJytCxgX   
...                            ...                     ...   
1204020                 Notch - EP  38O5Ys0W9PFS5K7dMb7yKb   
1204021                 Notch - EP  38O5Ys0W9PFS5K7dMb7yKb   
1204022                 Notch - EP  38O5Ys0W9PFS5K7dMb7yKb   
1204023                 Notch - EP  38O5Ys0W9PFS5K7dMb7yKb   
1204024                 Notch - EP  38O5Ys0W9PFS5K7dMb7yKb   

                          artists                  artist_ids  track_number   
0        Rage Against The Machine  ['2d0hyoQ5ynDBnkvAbJKORj']             1  \
1        Rage Against The Machine  ['2d0hyoQ5ynDBnkvAbJKORj']             2   
2        Rage Against The Machine  ['2d0hyoQ5ynDBnkvAbJKORj']             3   
3        Rage Against The Machine  ['2d0hyoQ5ynDBnkvAbJKORj']             4   
4        Rage Against The Machine  ['2d0hyoQ5ynDBnkvAbJKORj']             5   
...                           ...                         ...           ...   
1204020                   FVLCRVM  ['7AjItKsRnEYRSiBt2OxK1y']             2   
1204021                   FVLCRVM  ['7AjItKsRnEYRSiBt2OxK1y']             3   
1204022                   FVLCRVM  ['7AjItKsRnEYRSiBt2OxK1y']             4   
1204023                   FVLCRVM  ['7AjItKsRnEYRSiBt2OxK1y']             5   
1204024                   FVLCRVM  ['7AjItKsRnEYRSiBt2OxK1y']             6   

         disc_number  explicit  danceability  ...  speechiness  acousticness   
0                  1     False         0.470  ...       0.0727       0.02610  \
1                  1      True         0.599  ...       0.1880       0.01290   
2                  1     False         0.315  ...       0.4830       0.02340   
3                  1      True         0.440  ...       0.2370       0.16300   
4                  1     False         0.426  ...       0.0701       0.00162   
...              ...       ...           ...  ...          ...           ...   
1204020            1     False         0.264  ...       0.0672       0.00935   
1204021            1     False         0.796  ...       0.0883       0.10400   
1204022            1     False         0.785  ...       0.0564       0.03040   
1204023            1     False         0.665  ...       0.0409       0.00007   
1204024            1     False         0.736  ...       0.0539       0.01680   

         instrumentalness  liveness  valence    tempo  duration_ms   
0                0.000011    0.3560    0.503  117.906       210133  \
1                0.000071    0.1550    0.489  103.680       206200   
2                0.000002    0.1220    0.370  149.749       298893   
3                0.000004    0.1210    0.574   96.752       213640   
4                0.105000    0.0789    0.539  127.059       205600   
...                   ...       ...      ...      ...          ...   
1204020          0.002240    0.3370    0.415  159.586       276213   
1204021          0.644000    0.0749    0.781  121.980       363179   
1204022          0.918000    0.0664    0.467  1

In [ ]:
df_spotify.columns

Index(['id', 'name', 'album', 'album_id', 'artists', 'artist_ids',
       'track_number', 'disc_number', 'explicit', 'danceability', 'energy',
       'key', 'loudness', 'mode', 'speechiness', 'acousticness',
       'instrumentalness', 'liveness', 'valence', 'tempo', 'duration_ms',
       'time_signature', 'year', 'release_date'],
      dtype='object')

In [ ]:
df_spotify = df_spotify.drop(['id', 'album', 'album_id', 'artist_ids', 'track_number', 'disc_number', 'duration_ms', 'year'], axis=1)

In [ ]:
df_spotify.columns

Index(['name', 'artists', 'explicit', 'danceability', 'energy', 'key',
       'loudness', 'mode', 'speechiness', 'acousticness', 'instrumentalness',
       'liveness', 'valence', 'tempo', 'time_signature', 'release_date'],
      dtype='object')

In [ ]:
df_triplets_metadata.columns

Index(['Unnamed: 0', 'user', 'listening_count', 'title', 'release',
       'artist_name', 'duration', 'artist_familiarity', 'artist_hotttnesss',
       'year', 'shs_perf', 'shs_work'],
      dtype='object')

In [ ]:
#df_triplets_metadata = df_triplets_metadata.drop(['Unnamed: 0', 'song_id', 'track_id', 'artist_id', 'artist_mbid', 'track_7digitalid'], axis=1)
df_triplets_metadata = df_triplets_metadata.rename(columns = {'title' :'song_name'})

In [ ]:
df_triplets_metadata.columns

Index(['Unnamed: 0', 'user', 'listening_count', 'song_name', 'release',
       'artist_name', 'duration', 'artist_familiarity', 'artist_hotttnesss',
       'year', 'shs_perf', 'shs_work'],
      dtype='object')

In [ ]:
df_spotify = df_spotify.rename(columns={'artists' : 'artist_name', 'name' : 'song_name'})

df_spotify.columns

Index(['song_name', 'artist_name', 'explicit', 'danceability', 'energy', 'key',
       'loudness', 'mode', 'speechiness', 'acousticness', 'instrumentalness',
       'liveness', 'valence', 'tempo', 'time_signature', 'release_date'],
      dtype='object')

In [ ]:
#df_metadata = df_metadata.drop_duplicates(subset = ['song_id'], keep='first')
df_spotify.duplicated(subset=['song_name', 'artist_name']).sum()


62469

In [ ]:
df_spotify[df_spotify.duplicated(subset=['song_name', 'artist_name'])]

song_name                  artist_name   
367                               Rock Me Baby                Johnny Winter  \
371                                Rock & Roll                Johnny Winter   
945                              8-Ball Deluxe                 7 Year Bitch   
1056                              Looking Good                    Magic Sam   
1291                                      Lola  Iggy Azalea', 'Alice Chater   
...                                        ...                          ...   
1203928                                Фак опс                        FEDUK   
1203952                     U R the Best Thing                        Qeuyl   
1203984  Levitating (feat. DaBaby) - KUU Remix    Dua Lipa', 'KUU', 'DaBaby   
1204015                          Drop the Game          The Dartmouth Aires   
1204017                     Wayfaring Stranger          The Dartmouth Aires   

         explicit  danceability  energy  key  loudness  mode  speechiness   
367         False         0.483   0.744    7    -9.683     1       0.0562  \
371         False         0.418   0.745    7   -10.642     1       0.0515   
945         False         0.424   0.845    4    -6.272     1       0.0551   
1056        False         0.340   0.977    7   -11.136     0       0.5190   
1291        False         0.770   0.564   10    -9.051     1       0.1800   
...           ...           ...     ...  ...       ...   ...          ...   
1203928      True         0.673   0.646    9    -8.450     0       0.4320   
1203952     False         0.639   0.509    5    -6.583     1       0.0599   
1203984     False         0.734   0.890    2    -6.069     1       0.0526   
1204015     False         0.398   0.503    4    -6.750     0       0.0311   
1204017     False         0.262   0.351    2    -8.575     1       0.0379   

         acousticness  instrumentalness  liveness  valence    tempo   
367           0.30400          0.093500    0.1330    0.647   95.477  \
371           0.02130          0.166000    0.1160    0.535  142.639   
945           0.03960          0.000000    0.3420    0.791  122.911   
1056          0.31900          0.798000    0.9040    0.308  104.888   
1291          0.01660          0.000000    0.1450    0.449  141.816   
...               ...               ...       ...      ...      ...   
1203928       0.14400          0.000049    0.0631    0.576  140.001   
1203952       0.26400          0.000003    0.0552    0.449   70.009   
1203984       0.00305          0.000472    0.1180    0.361  111.975   
1204015       0.76400          0.000000    0.0954    0.362   76.508   
1204017       0.65600          0.000000    0.1130    0.285   90.301   

         time_signature release_date  
367                 4.0         1973  
371                 4.0         1973  
945                 4.0         2005  
1056                4.0   1990-01-01  
1291                4.0   2019-11-08  
...                 ...          ...  
1203928             4.0   2020-11-19  
1203952             4.0   2014-12-10  
1203984             4.0   2020-11-20  
1204015             4.0   2016-05-08  
1204017             4.0   2016-05-08  

[62469 rows x 16 columns]

In [ ]:
df_spotify[(df_spotify['song_name'] == 'Rock Me Baby') & (df_spotify['artist_name'] == 'Johnny Winter')]

song_name    artist_name  explicit  danceability  energy  key   
341     Rock Me Baby  Johnny Winter     False         0.284   0.706    4  \
367     Rock Me Baby  Johnny Winter     False         0.483   0.744    7   
123068  Rock Me Baby  Johnny Winter     False         0.281   0.798    4   

        loudness  mode  speechiness  acousticness  instrumentalness  liveness   
341      -10.447     0       0.0785         0.450            0.1450     0.150  \
367       -9.683     1       0.0562         0.304            0.0935     0.133   
123068    -8.714     0       0.0827         0.494            0.1920     0.110   

        valence    tempo  time_signature release_date  
341       0.696  190.284             4.0         1973  
367       0.647   95.477             4.0         1973  
123068    0.704  190.763             4.0         1969

In [ ]:
df_spotify[(df_spotify['song_name'] == 'Wayfaring Stranger') & (df_spotify['artist_name'] == 'The Dartmouth Aires')]

song_name          artist_name  explicit  danceability   
1204007  Wayfaring Stranger  The Dartmouth Aires     False         0.263  \
1204017  Wayfaring Stranger  The Dartmouth Aires     False         0.262   

         energy  key  loudness  mode  speechiness  acousticness   
1204007   0.352   11    -8.548     0       0.0372         0.658  \
1204017   0.351    2    -8.575     1       0.0379         0.656   

         instrumentalness  liveness  valence   tempo  time_signature   
1204007               0.0     0.114    0.283  90.096             4.0  \
1204017               0.0     0.113    0.285  90.301             4.0   

        release_date  
1204007   2017-12-03  
1204017   2016-05-08

In [ ]:
# let's drop irrelevant same song and artist irrelevant distinct values
df_spotify = df_spotify.drop_duplicates(subset=['song_name', 'artist_name'], keep= 'first')
## check remaining duplicates of (song_name, artist_name)
df_spotify[['song_name', 'artist_name']].duplicated().sum()

0

In [ ]:
## Let's check previous checkpoints
display(df_spotify[(df_spotify['song_name'] == 'Rock Me Baby') & (df_spotify['artist_name'] == 'Johnny Winter')])
display(df_spotify[(df_spotify['song_name'] == 'Wayfaring Stranger') & (df_spotify['artist_name'] == 'The Dartmouth Aires')])

song_name    artist_name  explicit  danceability  energy  key   
341  Rock Me Baby  Johnny Winter     False         0.284   0.706    4  \

     loudness  mode  speechiness  acousticness  instrumentalness  liveness   
341   -10.447     0       0.0785          0.45             0.145      0.15  \

     valence    tempo  time_signature release_date  
341    0.696  190.284             4.0         1973

song_name          artist_name  explicit  danceability   
1204007  Wayfaring Stranger  The Dartmouth Aires     False         0.263  \

         energy  key  loudness  mode  speechiness  acousticness   
1204007   0.352   11    -8.548     0       0.0372         0.658  \

         instrumentalness  liveness  valence   tempo  time_signature   
1204007               0.0     0.114    0.283  90.096             4.0  \

        release_date  
1204007   2017-12-03

## Now we can merge df_triplets_metadata with df_spotify

In [ ]:
df_triplets_metadata_spotify = pd.merge(df_triplets_metadata, df_spotify, on = ['song_name', 'artist_name'], how = 'inner')

In [ ]:
df_triplets_metadata_spotify

Unnamed: 0                                      user   
0              7300  b80344d063b5ccb3212f76538f3d9e43d87dca9e  \
1              7301  9fba771d9731561eba47216f6fbfc0023d88641b   
2              7302  85952991b8e3ca5803a08b0b2f9c6d71abf9bb5b   
3              7303  537340ff896dea11328910013cfe759413e1eeb3   
4              7304  8fce200f3912e9608e3b1463cdb9c3529aab5c08   
...             ...                                       ...   
4982515    48373518  3796a24e109961914e04fc82f05e727751eba723   
4982516    48373525  61457d4f6b5053031c358de46929960f3d32d782   
4982517    48373526  61457d4f6b5053031c358de46929960f3d32d782   
4982518    48373537  bd0c3b42396ea8a1225eba1ac8c398b940e1b060   
4982519    48373585  6428bbc86c59bd5d1d289935056b57acd0e050ad   

         listening_count                   song_name   
0                      1                    Stronger  \
1                     19                    Stronger   
2                      1                    Stronger   
3                      2                    Stronger   
4                      2                    Stronger   
...                  ...                         ...   
4982515                1                        Dime   
4982516                1       The Long Conversation   
4982517                1  That's the Way That It Was   
4982518                3          I'll Close My Eyes   
4982519                5                      Rowena   

                                                  release   
0                                              Graduation  \
1                                              Graduation   
2                                              Graduation   
3                                              Graduation   
4                                              Graduation   
...                                                   ...   
4982515                                  20th Anniversary   
4982516                               The Way That It Was   
4982517                               The Way That It Was   
4982518                                       Runnin Wild   
4982519  High Wide & Handsome - The Charlie Poole Project   

                   artist_name   duration  artist_familiarity   
0                   Kanye West  311.84934            0.877214  \
1                   Kanye West  311.84934            0.877214   
2                   Kanye West  311.84934            0.877214   
3                   Kanye West  311.84934            0.877214   
4                   Kanye West  311.84934            0.877214   
...                        ...        ...                 ...   
4982515           Jerry Rivera  284.29016            0.650177   
4982516       Pierre de Reeder  184.65914            0.511732   
4982517       Pierre de Reeder  167.28771            0.511732   
4982518             Mike Jones  265.79546            0.793605   
4982519  Loudon Wainwright III  152.13669            0.661080   

         artist_hotttnesss  year  ...  loudness  mode  speechiness   
0                 1.082503  2007  ...    -7.933     0       0.1760  \
1                 1.082503  2007  ...    -7.933     0       0.1760   
2                 1.082503  2007  ...    -7.933     0       0.1760   
3                 1.082503  2007  ...    -7.933     0       0.1760   
4                 1.082503  2007  ...    -7.933     0       0.1760   
...                    ...   ...  ...       ...   ...          ...   
4982515           0.404963  2001  ...    -9.949     1       0.0403   
4982516           0.344567  2008  ...   -10.025     1       0.0273   
4982517           0.344567  2008  ...    -5.848     1       0.0370   
4982518           0.426318     0  ...   -24.078     1       0.0350   
4982519           0.442766  2009  ...   -19.687     1       0.0384   

         acousticness  instrumentalness  liveness  valence    tempo   
0             0.00763          0.000000     0.526    0.495  103.977  \
1             0.00763          0.000000     0.526    0.495

In [ ]:
print(len(df_triplets_metadata.index))
print(len(df_triplets_metadata_spotify.index))

48373586
4982520


From 48,373,586 rows (~ 11GB), we passed to    4,982,520 rows

In [ ]:
#DESTINATION_PATH = DATA_DIR / 'triplets_metadata_spotify.csv'
#df_triplets_metadata_spotify.to_csv(DESTINATION_PATH)

## We definitely preserved enough listening events counts per user through this merge

In [39]:
FILE_PATH = DATA_DIR/'triplets_metadata_spotify.csv'

df_triplets_metadata_spotify = pd.read_csv(FILE_PATH)

In [40]:
# Uncomment to check number of listening events per test user
df_triplets_metadata_spotify[df_triplets_metadata_spotify['user']=="b80344d063b5ccb3212f76538f3d9e43d87dca9e"]
#df_triplets_metadata_spotify[df_triplets_metadata_spotify['user']=="9fba771d9731561eba47216f6fbfc0023d88641b"]
#df_triplets_metadata_spotify[df_triplets_metadata_spotify['user']=="85952991b8e3ca5803a08b0b2f9c6d71abf9bb5b"]
#df_triplets_metadata_spotify[df_triplets_metadata_spotify['user']=="537340ff896dea11328910013cfe759413e1eeb3"]
#df_triplets_metadata_spotify[df_triplets_metadata_spotify['user']=="8fce200f3912e9608e3b1463cdb9c3529aab5c08"]

Unnamed: 0                                      user  listening_count  \
0               0  b80344d063b5ccb3212f76538f3d9e43d87dca9e                1   
18315       18315  b80344d063b5ccb3212f76538f3d9e43d87dca9e                1   
20077       20077  b80344d063b5ccb3212f76538f3d9e43d87dca9e                1   
22873       22873  b80344d063b5ccb3212f76538f3d9e43d87dca9e                1   
23610       23610  b80344d063b5ccb3212f76538f3d9e43d87dca9e                1   
27188       27188  b80344d063b5ccb3212f76538f3d9e43d87dca9e                1   
30658       30658  b80344d063b5ccb3212f76538f3d9e43d87dca9e                1   
37145       37145  b80344d063b5ccb3212f76538f3d9e43d87dca9e                1   
39049       39049  b80344d063b5ccb3212f76538f3d9e43d87dca9e                1   
40034       40034  b80344d063b5ccb3212f76538f3d9e43d87dca9e                1   
45162       45162  b80344d063b5ccb3212f76538f3d9e43d87dca9e                1   
57340       57340  b80344d063b5ccb3212f76538f3d9e43d87dca9e                1   
59295       59295  b80344d063b5ccb3212f76538f3d9e43d87dca9e                1   
63232       63232  b80344d063b5ccb3212f76538f3d9e43d87dca9e                1   
71711       71711  b80344d063b5ccb3212f76538f3d9e43d87dca9e                1   

                  song_name                                         release  \
0                  Stronger                                      Graduation   
18315        Stacked Actors                   There Is Nothing Left To Lose   
20077               Clarity  As/Is: Cleveland/Cincinnati_ OH - 8/03-8/04/04   
22873        Gimme Stitches                   There Is Nothing Left To Lose   
23610              Breakout                   There Is Nothing Left To Lose   
27188           Ragged Wood                                     Fleet Foxes   
30658               Mykonos                                       Sun Giant   
37145               Warning                           Live in Malaysia 2004   
39049  All That We Perceive                      The Richest Man In Babylon   
40034           Are You In?                          Monuments And Melodies   
45162                 Drive                                   Make Yourself   
57340             Generator                   There Is Nothing Left To Lose   
59295   He Doesn't Know Why                                     Fleet Foxes   
63232   Bigger Isn't Better                        Born on the Wrong Planet   
71711             Sun Giant                                       Sun Giant   

                      artist_name   duration  artist_familiarity  \
0                      Kanye West  311.84934            0.877214   
18315                Foo Fighters  256.46975            0.839275   
20077                  John Mayer  548.88444            0.837948   
22873                Foo Fighters  222.19710            0.839275   
23610                Foo Fighters  200.80281            0.839275   
27188                 Fleet Foxes  307.17342            0.775166   
30658                 Fleet Foxes  275.27791            0.775166   
37145                     Incubus  289.54077            0.899280   
39049        Thievery Corporation  226.03710            0.778080   
40034                     Incubus  263.60118            0.899280   
45162                     Incubus  232.46322            0.899280   
57340                Foo Fighters  227.55220            0.839275   
59295                 Fleet Foxes  200.46322            0.775166   
63232  The String Cheese Incident  392.35873            0.646637   
71711                 Fleet Foxes  134.29506            0.786229   

       artist_hotttnesss  year  ...  loudness  mode  speechiness  \
0               1.082503  2007  ...    -7.933     0       0.1760   
18315           0.550762  1999  ...    -5.145     1       0.0500   
20077           0.787679     0  ...    -3.551     1       0.0384   
22873           0.550762  1999  ...    -4.215     1       0.0685   
23610           0.550762  1999  

In [ ]:
## Suppression of cold_starters by selecting 1e+5 and 1e+4 largest listeners
## results in dataframes of respectively  1.771.670  and 290.274 rows with a minimal listening counts of 35 and 116 


## first 1e+5 "extreme users" who can listen to a single song more than a thousand times
df_filter_1 = df_triplets_metadata_spotify.groupby('user')\
                                        .agg({'listening_count' : 'sum'})\
                                        .rename(columns = {'listening_count' : 'listening_count_sum'})\
                                        .sort_values(by=['listening_count_sum'], ascending=False)\
                                        .reset_index()\
                                        .head(100000)
#df_filter_1 



## first 1e+4 "extreme users" who can listen to a single song more than a thousand times

df_filter_2 = df_triplets_metadata_spotify.groupby('user')\
                                        .agg({'listening_count' : 'sum'})\
                                        .rename(columns = {'listening_count' : 'listening_count_sum'})\
                                        .sort_values(by=['listening_count_sum'], ascending=False)\
                                        .reset_index()\
                                        .head(10000)


## first 1e+4 users who listen multiple songs
'''
df_filter_2 = df_triplets_metadata_spotify.groupby('user')\
                                        .agg({'listening_count' : 'sum', 'listening_count' :'count'})\
                                        .rename(columns = {'listening_count' : 'listening_count_sum'})\
                                        .sort_values(by=['listening_count_sum'], ascending=False)\
                                        .head(10000)
'''

df_filter_2.head(11)

user  listening_count_sum
0   f0b5c784daaa3c7d50acbb3723c7dd649db2b231                 1763
1   22e08d5e101ab5b86dc394856d508e175a5242a6                 1603
2   af3ee32357049dd96231238bd1b019e8142ee6aa                 1553
3   6a6d346cc92ee699a765a06fd97db74b864a8129                 1508
4   3fa44653315697f42410a30cb766a4eb102080bb                 1506
5   6a46aee45cc177cf8e2025e59d21c7939902deee                 1379
6   716ed1ec67d67bfa05db3ffeb641d13f46dca6ec                 1143
7   9755e6e2faf1ba2e1e46f8227690847511425bab                 1085
8   44d6db05e087361c30a3862db756b9530b5ed14d                 1068
9   19a7ec5c51a370817f99cf18decde4b8f469bfd3                 1056
10  9d17a429365653228049e8fe3d5968d4cd5dc6fe                 1045

In [ ]:
df_triplets_metadata_spotify_sample1 = df_triplets_metadata_spotify[df_triplets_metadata_spotify["user"].isin(df_filter_1['user'])]\
                                                                                                        .sort_values(by = 'user')
#df_triplets_metadata_spotify_sample1

df_triplets_metadata_spotify_sample2 = df_triplets_metadata_spotify[df_triplets_metadata_spotify["user"].isin(df_filter_2['user'])]\
                                                                                                        .sort_values(by = 'user')
df_triplets_metadata_spotify_sample1

Unnamed: 0                                      user   
4291273     4291273  00020e8ba3f9041deed64ec9c60b26ff6bf41c66  \
1106289     1106289  00020e8ba3f9041deed64ec9c60b26ff6bf41c66   
2918176     2918176  00020e8ba3f9041deed64ec9c60b26ff6bf41c66   
1534204     1534204  00020e8ba3f9041deed64ec9c60b26ff6bf41c66   
4080426     4080426  00020e8ba3f9041deed64ec9c60b26ff6bf41c66   
...             ...                                       ...   
3285759     3285759  ffffcfeb0c1b66bd212ea58d918c7dc62fb9c3a5   
3114703     3114703  ffffcfeb0c1b66bd212ea58d918c7dc62fb9c3a5   
135733       135733  ffffcfeb0c1b66bd212ea58d918c7dc62fb9c3a5   
3890558     3890558  ffffcfeb0c1b66bd212ea58d918c7dc62fb9c3a5   
1070395     1070395  ffffcfeb0c1b66bd212ea58d918c7dc62fb9c3a5   

         listening_count              song_name   
4291273                3                  Sadie  \
1106289                1             Octavo Día   
2918176                9   Twist In My Sobriety   
1534204               42            A Lo Cubano   
4080426                1               Lowrider   
...                  ...                    ...   
3285759                5       Dust in The Wind   
3114703                3                Too Bad   
135733                 2               Marry Me   
3890558                3  Coat Check Dream Song   
1070395                1  The Laws Have Changed   

                                                   release   
4291273                                            12 Play  \
1106289                              Shakira MTV Unplugged   
2918176        Bandits (Music from the MGM Motion Picture)   
1534204                                        A Lo Cubano   
4080426                                     Stoned Raiders   
...                                                    ...   
3285759  Essential Rock - Definitive Rock Classics And ...   
3114703                                     Silver Side Up   
135733                              Save Me_ San Francisco   
3890558                                          Cassadaga   
1070395                                   Electric Version   

                   artist_name   duration  artist_familiarity   
4291273               R. Kelly  270.02730            0.811092  \
1106289                Shakira  363.38893            0.833179   
2918176         Tanita Tikaram  293.51138            0.628921   
1534204                Orishas  243.66975            0.678548   
4080426           Cypress Hill  401.39710            0.793110   
...                        ...        ...                 ...   
3285759                 Kansas  202.29179            0.762318   
3114703             Nickelback  232.20200            0.847452   
135733                   Train  205.45261            0.838886   
3890558            Bright Eyes  246.98730            0.796082   
1070395  The New Pornographers  206.81098            0.708589   

         artist_hotttnesss  year  ...  loudness  mode  speechiness   
4291273           0.783843  1993  ...   -10.706     0       0.0556  \
1106289           0.682263  1998  ...    -5.904     1       0.0341   
2918176           0.411234  1988  ...    -8.084     0       0.0244   
1534204           0.525053  1999  ...    -8.155     1       0.2520   
4080426           0.555789  2001  ...    -7.200     0       0.1990   
...                    ...   ...  ...       ...   ...          ...   
3285759           0.484567  1977  ...   -13.780     1       0.0299   
3114703           0.779968  2001  ...    -5.209     1       0.0388   
135733            0.783677  2009  ...    -9.414     1       0.0276   
3890558           0.517772  2007  ...    -7.692     1       0.0356   
1070395           0.523546  2003  ...    -3.140     1       0.0385   

         acousticness  instrumentalness  liveness  valence    tempo   
4291273       0.24400          0.000000    0.1340    0.444  161.812  \
1106289       0.30800          0.000058    0.2160    0.208   80.761   
2918176       0.05580          0.10

In [ ]:
#DESTINATION_PATH = DATA_DIR / 'triplets_metadata_spotify_1e+5.csv'
#df_triplets_metadata_spotify_sample1.to_csv(DESTINATION_PATH)

In [ ]:
#DESTINATION_PATH = DATA_DIR / 'triplets_metadata_spotify_1e+4.csv'
#df_triplets_metadata_spotify_sample2.to_csv(DESTINATION_PATH)